<?xml version="1.0" encoding="utf-8"?><Database Name="Auction" Class="dbQLDGDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-A8A7OPE\MSSQLSERVER01;Initial Catalog=Auction;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="AuctionConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Asset" Member="Assets">
    <Type Name="Asset">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Asset_Lot" Member="Lots" ThisKey="ID" OtherKey="AssetID" Type="Lot" />
    </Type>
  </Table>
  <Table Name="dbo.ATM" Member="ATMs">
    <Type Name="ATM">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ATMCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ATMFullName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BankId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Bank_ATM" Member="Bank" ThisKey="BankId" OtherKey="Id" Type="Bank" IsForeignKey="true" />
      <Association Name="User_ATM" Member="User" ThisKey="UserID" OtherKey="ID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Auction" Member="Auctions">
    <Type Name="Auction">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RegisterBidID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PriceBid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BidTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="RegisterBid_Auction" Member="RegisterBid" ThisKey="RegisterBidID" OtherKey="ID" Type="RegisterBid" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Banks" Member="Banks">
    <Type Name="Bank">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="Bank_ATM" Member="ATMs" ThisKey="Id" OtherKey="BankId" Type="ATM" />
    </Type>
  </Table>
  <Table Name="dbo.Categories" Member="Categories">
    <Type Name="Category">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="SiteTile" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="MetaKeywords" Type="System.String" DbType="NVarChar(158)" CanBeNull="true" />
      <Column Name="MetaDescription" Type="System.String" DbType="NVarChar(158)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Category_Lot" Member="Lots" ThisKey="ID" OtherKey="CateID" Type="Lot" />
    </Type>
  </Table>
  <Table Name="dbo.Lot" Member="Lots">
    <Type Name="Lot">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="MiniumBid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StartingPrice" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AdvanceDesposit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ParticipationFee" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HostLot" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TimeForRegisterEnd" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TimeForBidEnd" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TimeForBidStart" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TimeForRegisterStart" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AssetID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CateID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HostName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Location" Type="System.String" DbType="NVarChar(158)" CanBeNull="true" />
      <Column Name="ViewInTime" Type="System.String" DbType="NVarChar(158)" CanBeNull="true" />
      <Column Name="SiteTile" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Association Name="Lot_LotAttachment" Member="LotAttachments" ThisKey="ID" OtherKey="LotID" Type="LotAttachment" />
      <Association Name="Lot_Product" Member="Products" ThisKey="ID" OtherKey="LotID" Type="Product" />
      <Association Name="Lot_RegisterBid" Member="RegisterBids" ThisKey="ID" OtherKey="LotID" Type="RegisterBid" />
      <Association Name="Asset_Lot" Member="Asset" ThisKey="AssetID" OtherKey="ID" Type="Asset" IsForeignKey="true" />
      <Association Name="Category_Lot" Member="Category" ThisKey="CateID" OtherKey="ID" Type="Category" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LotAttachments" Member="LotAttachments">
    <Type Name="LotAttachment">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(158)" CanBeNull="true" />
      <Column Name="AttachmentLink" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="LotID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Lot_LotAttachment" Member="Lot" ThisKey="LotID" OtherKey="ID" Type="Lot" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Organizations" Member="Organizations">
    <Type Name="Organization">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(158)" CanBeNull="true" />
      <Column Name="TaxCode" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="IssuedOn" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Location" Type="System.String" DbType="NVarChar(158)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="User_Organization" Member="User" ThisKey="ID" OtherKey="ID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Products" Member="Products">
    <Type Name="Product">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UpdatedAt" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LotID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Product_ProductsImage" Member="ProductsImages" ThisKey="ID" OtherKey="ProductId" Type="ProductsImage" />
      <Association Name="Lot_Product" Member="Lot" ThisKey="LotID" OtherKey="ID" Type="Lot" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductsAttachments" Member="ProductsAttachments">
    <Type Name="ProductsAttachment">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Attachment" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="ProductId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductsImages" Member="ProductsImages">
    <Type Name="ProductsImage">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Image" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="Product_ProductsImage" Member="Product" ThisKey="ProductId" OtherKey="ID" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.RegisterBid" Member="RegisterBids">
    <Type Name="RegisterBid">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LotID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="RegisterBid_Auction" Member="Auctions" ThisKey="ID" OtherKey="RegisterBidID" Type="Auction" />
      <Association Name="Lot_RegisterBid" Member="Lot" ThisKey="LotID" OtherKey="ID" Type="Lot" IsForeignKey="true" />
      <Association Name="User_RegisterBid" Member="User" ThisKey="UserID" OtherKey="ID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Roles" Member="Roles">
    <Type Name="Role">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Association Name="Role_User" Member="Users" ThisKey="ID" OtherKey="RoleID" Type="User" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="RoleID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Gender" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Birthday" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="CMND" Type="System.String" DbType="NChar(13)" CanBeNull="true" />
      <Column Name="LocationCMND" Type="System.String" DbType="NVarChar(158)" CanBeNull="true" />
      <Column Name="DayCMND" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="User_ATM" Member="ATMs" ThisKey="ID" OtherKey="UserID" Type="ATM" />
      <Association Name="User_Organization" Member="Organization" ThisKey="ID" OtherKey="ID" Type="Organization" Cardinality="One" />
      <Association Name="User_RegisterBid" Member="RegisterBids" ThisKey="ID" OtherKey="UserID" Type="RegisterBid" />
      <Association Name="User_UsersImage" Member="UsersImages" ThisKey="ID" OtherKey="UsersID" Type="UsersImage" />
      <Association Name="Role_User" Member="Role" ThisKey="RoleID" OtherKey="ID" Type="Role" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UsersImages" Member="UsersImages">
    <Type Name="UsersImage">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UsersID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Image" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="User_UsersImage" Member="User" ThisKey="UsersID" OtherKey="ID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
</Database>